### PR TITLE
Add step-by-step instructions for the curious but unsavvy.

### PR DESCRIPTION
**Pull request by dvrensk**
I haven't done Java for years and never saw lein before.  This instruction should get people like me over the threshold.  "Researching" this took the better part of a day, so I'd say it would be valuable to people out there.

### CODE REVIEW

**Comment by algernon** [comment]
These instructions saved me quite a bit of time, thanks for that!

**Comment by nextuser** [comment]
1. I think the project need more contributor to add document about tutorial and manual,
   we need more tutorial on different platform. 
   step by step and valid every step,
   java starter /clojure starter/python starter  should in diferenct section.

I have tried to run storm in suse 11 but failed. 
2. too many project dependencies is involved in this project. 0mq,jzmq ,clojure,,zookeeper and so on , 
3. the project is so difficult to start that tow little developer will use it.

**Comment by dalbert** [comment]
It would help if these instructions were included or referenced on the storm and storm-starter projects pages. I didn't know where to begin (I started with storm) and only found these instructions after having stumbled through on my own. I'd even documented my own steps (http://goddamndave.com/post/15779122918/first-baby-steps-with-storm) to help others before finding that it had already been documented here.

**Comment by miguno** [comment]
I added many of the points in the original pull request (dated two years ago) to the README.  See commit https://github.com/nathanmarz/storm-starter/commit/b9c57eb9ac20cbb44af0c4fd64c8de3f219bf3c3.

If there is anything missing -- given today's code in storm-starter -- please open a new pull request so that we can merge it in.

**Pull request closed without merging**
