### PR TITLE
Complete refactoring of the Rolling Count example

### PR DESCRIPTION
**Pull request by miguno**
Hi Nathan,

as discussed here is the new implementation, see details below.

I have also updated m2-pom.xml and made sure the build and tests execute successfully when run via Maven -- I haven't touched project.clj though. 

Of course, the Maven example commands in the README are still working properly.  For instance, to run the new Rolling Count example from CLI:

$ mvn -f m2-pom.xml compile exec:java -Dexec.classpathScope=compile -Dexec.mainClass=storm.starter.RollingTopWords

Best,
Michael

---

The new implementation separates the various concerns formerly mixed up in the
example code.  Also, we are now using tick tuples (introduced in Storm 0.8)
instead of spawning manual threads for carrying out periodical tasks.

Lastly, we add 192 unit tests for the new implementation that brings the test
coverage for the Rolling Count from 0% to almost 100%.

Note: Adding those unit tests required changes to the build (m2-pom.xml),
notably new test dependencies and moving the existing Java code from src/jvm/*
to src/jvm/main/*.  The latter was required so that the test runner triggered
by Maven can tell code (src/jvm/main) and tests (src/jvm/test) apart.

### CODE REVIEW

**Comment by nathanmarz** [comment]
This looks great. I'm not a fan of the src/jvm -> src/jvm/main change, especially as it breaks compatibility with leiningen. Is it possible to configure Maven to look in test/jvm instead for unit tests instead of src/jvm/test?

**Comment by miguno** [comment]
Yes, configuring maven to look for tests in `test/jvm` should be possible.  These lines in m2-pom.xml should do it:

```
<sourceDirectory>src/jvm</sourceDirectory>
<testSourceDirectory>test/jvm</testSourceDirectory>
```

I will verify tomorrow and send you an updated pull request if everything works.

**Comment by miguno** [comment]
I updated the pull request, see below.  `mvn -f m2-pom.xml clean test` works as expected with the change.

FYI: Since I have no experience with leiningen I didn't touch project.clj.  I tried updating it, too, but for some reason `lein test` never picked up any unit tests from `test/jvm` even though I played with various permutations of `test-paths` and `java-source-path` / `java-source-paths`.

**Comment by nathanmarz** [comment]
Good stuff, thanks!

**Comment by miguno** [comment]
You're welcome.

Quick follow-up: I ran `lein test` after your latest changes to project.clj, but for some reason lein is not executing any unit tests (`mvn -f m2-pom.xml test` does).

```
$ lein test

Testing user

Ran 0 tests containing 0 assertions.
0 failures, 0 errors.
```

**Comment by nathanmarz** [comment]
"lein test" is completely different than "mvn test" – it looks for Clojure tests to run. I wouldn't worry about this.

**Pull request merged**
